import type {
  AIComplianceResult,
  AIComplianceStatus,
  AIRmfPhase,
  AISystem,
  Manifest,
} from "../types.js";
import { getAICrossMapping } from "./cross-map.js";

/**
 * EU AI Act framework definition. Each control represents one article (or
 * a tight article grouping) that a provider of an AI system can be audited
 * against. Checks run against the scanner's manifest; many obligations are
 * program-level and resolve to `partial` with instructional evidence rather
 * than a hard pass/fail — the intent is to surface the obligation so a GRC
 * owner can close the gap out-of-band.
 *
 * Risk-tier scoping follows Article 6 + Annex III: most high-risk
 * obligations (Art. 9/11/12/13/14/15/27/60/73) are marked `not-applicable`
 * when no high-risk system is detected. Article 5 (prohibited) always
 * applies. Article 50 (user transparency) applies whenever any system is
 * at least "limited" tier.
 *
 * References: Regulation (EU) 2024/1689, "EU AI Act". Article numbers
 * follow the published text as of Jan 2026.
 */

export interface AIFrameworkControl {
  id: string;
  article: number;
  title: string;
  phase: AIRmfPhase;
  description: string;
  check: (m: Manifest) => AIComplianceStatus;
  evidence: (m: Manifest) => string;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function systemsAtOrAbove(m: Manifest, tiers: AISystem["riskTier"][]): AISystem[] {
  return m.aiSystems.filter(s => s.riskTier && tiers.includes(s.riskTier));
}
const hasAny = (m: Manifest) => m.aiSystems.length > 0;
const prohibitedSystems = (m: Manifest) => systemsAtOrAbove(m, ["prohibited"]);
const highRiskSystems = (m: Manifest) => systemsAtOrAbove(m, ["high", "prohibited"]);
const transparencyScopeSystems = (m: Manifest) =>
  systemsAtOrAbove(m, ["limited", "high", "prohibited"]);
const euMarketHighRisk = (m: Manifest) =>
  highRiskSystems(m).filter(s => s.euMarket === true);

function listProviders(systems: AISystem[]): string {
  if (systems.length === 0) return "—";
  return systems.map(s => `${s.provider} (${s.riskTier ?? "unclassified"})`).join(", ");
}

// ─── Control definitions ────────────────────────────────────────────────────

export const EU_AI_ACT_CONTROLS: AIFrameworkControl[] = [
  // ═══ GOVERN ═════════════════════════════════════════════════════════════
  {
    id: "ART-4",
    article: 4,
    title: "AI literacy",
    phase: "Govern",
    description: "Staff developing or operating AI systems must have sufficient AI literacy.",
    check: (m) => hasAny(m) ? "partial" : "not-applicable",
    evidence: (m) =>
      hasAny(m)
        ? `AI systems detected (${m.aiSystems.length}). AI literacy is a program-level obligation — document the training your developers and deployers receive.`
        : "No AI systems detected in this repo.",
  },

  {
    id: "ART-9",
    article: 9,
    title: "Risk management system",
    phase: "Govern",
    description: "Providers of high-risk AI systems must establish and maintain a risk management system across the lifecycle.",
    check: (m) => {
      if (highRiskSystems(m).length === 0) return "not-applicable";
      return "partial";
    },
    evidence: (m) => {
      const hr = highRiskSystems(m);
      if (hr.length === 0) return "No high-risk AI systems detected — Article 9 does not apply.";
      return `High-risk systems detected: ${listProviders(hr)}. Cybersecurity risk assessment is generated by the scanner; AI-specific risk management (model failure modes, drift, adversarial robustness) should be documented separately and reviewed on each release.`;
    },
  },

  {
    id: "ART-10",
    article: 10,
    title: "Data and data governance",
    phase: "Govern",
    description: "Training, validation, and testing datasets for high-risk AI must meet quality criteria and be governed (bias, lineage, lawful basis).",
    check: (m) => {
      if (highRiskSystems(m).length === 0) return "not-applicable";
      if (m.artifacts.privacyPolicy === "missing") return "fail";
      return "partial";
    },
    evidence: (m) => {
      if (highRiskSystems(m).length === 0) return "No high-risk AI systems detected.";
      if (m.artifacts.privacyPolicy === "missing") {
        return "No privacy policy present — required baseline for documenting data sources and lawful basis.";
      }
      return `Privacy policy: ${m.artifacts.privacyPolicy}. Verify it covers training/validation/testing data sources, data subject rights, and bias-testing procedures for AI data flows.`;
    },
  },

  // ═══ MAP ════════════════════════════════════════════════════════════════
  {
    id: "ART-5",
    article: 5,
    title: "Prohibited AI practices",
    phase: "Map",
    description: "Placing on the market or using AI for social scoring, subliminal manipulation, real-time biometric identification in public, or exploiting vulnerabilities is prohibited.",
    check: (m) => prohibitedSystems(m).length > 0 ? "fail" : "pass",
    evidence: (m) => {
      const p = prohibitedSystems(m);
      if (p.length > 0) {
        const locs = p.map(s => `${s.provider} @ ${s.location}`).join("; ");
        return `Flagged as potentially prohibited: ${locs}. Verify purpose; if misclassified, override in .grc/config.yml via ai_systems.risk_tier. If correct, placing this on the EU market is prohibited.`;
      }
      if (hasAny(m)) return "No AI systems classified as prohibited.";
      return "No AI systems detected.";
    },
  },

  {
    id: "ART-11",
    article: 11,
    title: "Technical documentation",
    phase: "Map",
    description: "Providers of high-risk AI must maintain technical documentation (model card, system description, training data, performance, known limits) before placing on the market.",
    check: (m) => {
      if (highRiskSystems(m).length === 0) return "not-applicable";
      if (m.artifacts.modelCards === "present") return "partial";
      return "fail";
    },
    evidence: (m) => {
      const hr = highRiskSystems(m);
      if (hr.length === 0) return "No high-risk AI systems detected — technical documentation not required.";
      if (m.artifacts.modelCards === "present") {
        return `Model card templates generated in model-cards/ for high-risk systems: ${listProviders(hr)}. Complete the placeholder sections (intended purpose, accuracy metrics, specific oversight measures) before considering this article fully satisfied.`;
      }
      return `No model card artifact present. Required for: ${listProviders(hr)}. Re-run the scanner with AI systems detected to generate templates at <output_dir>/model-cards/.`;
    },
  },

  // ═══ MEASURE ════════════════════════════════════════════════════════════
  {
    id: "ART-12",
    article: 12,
    title: "Record-keeping",
    phase: "Measure",
    description: "High-risk AI systems must automatically record events (logs) enabling traceability of operation.",
    check: (m) => {
      if (highRiskSystems(m).length === 0) return "not-applicable";
      return "partial";
    },
    evidence: (m) => {
      if (highRiskSystems(m).length === 0) return "No high-risk AI systems detected.";
      return "Automatic event logging is required for high-risk AI systems (six-month minimum retention recommended by guidance). Scanner cannot verify runtime logging — confirm your AI call paths emit structured logs with input/output hashes, user ID, and timestamps.";
    },
  },

  {
    id: "ART-15",
    article: 15,
    title: "Accuracy, robustness, cybersecurity",
    phase: "Measure",
    description: "High-risk AI must achieve appropriate accuracy, be robust to errors, and be cybersecure against attempts to alter use, outputs, or performance.",
    check: (m) => {
      if (highRiskSystems(m).length === 0) return "not-applicable";
      const crit = m.dependencies?.criticalVulnerabilities ?? 0;
      const high = m.dependencies?.highVulnerabilities ?? 0;
      const secrets = m.secretsScan.detected;
      const headers = m.securityHeaders;
      const headersOk = headers ? Object.values(headers).every(v => v === "present") : false;
      const httpsOk = m.https?.enforced === true;
      if (crit === 0 && high === 0 && !secrets && headersOk && httpsOk) return "pass";
      if (crit > 0 || secrets) return "fail";
      return "partial";
    },
    evidence: (m) => {
      if (highRiskSystems(m).length === 0) return "No high-risk AI systems detected.";
      const parts: string[] = [];
      parts.push(`Critical vulns: ${m.dependencies?.criticalVulnerabilities ?? "n/a"}`);
      parts.push(`High vulns: ${m.dependencies?.highVulnerabilities ?? "n/a"}`);
      parts.push(`Secrets in code: ${m.secretsScan.detected ? "detected" : "none"}`);
      parts.push(`HTTPS enforced: ${m.https?.enforced ?? "unknown"}`);
      if (m.securityHeaders) {
        const p = Object.values(m.securityHeaders).filter(v => v === "present").length;
        const t = Object.keys(m.securityHeaders).length;
        parts.push(`Security headers: ${p}/${t}`);
      }
      parts.push("Accuracy/robustness metrics (e.g. benchmark scores, adversarial testing) must be documented separately.");
      return parts.join(". ");
    },
  },

  {
    id: "ART-27",
    article: 27,
    title: "Fundamental Rights Impact Assessment (FRIA)",
    phase: "Measure",
    description: "Deployers of high-risk AI placed on the EU market in certain sectors must perform a FRIA before first use.",
    check: (m) => {
      if (euMarketHighRisk(m).length === 0) return "not-applicable";
      if (m.artifacts.fria === "present") return "partial";
      return "fail";
    },
    evidence: (m) => {
      const scoped = euMarketHighRisk(m);
      if (scoped.length === 0) return "No EU-market high-risk AI systems detected — FRIA not required.";
      if (m.artifacts.fria === "present") {
        return `FRIA template generated at fria.md for EU-market high-risk systems: ${listProviders(scoped)}. The template contains placeholder sections (affected persons, specific risks of harm, oversight measures) that must be completed by a human and signed before first use.`;
      }
      return `FRIA required for EU-market high-risk systems: ${listProviders(scoped)}. Scanner will generate a fria.md template on the next run.`;
    },
  },

  // ═══ MANAGE ═════════════════════════════════════════════════════════════
  {
    id: "ART-13",
    article: 13,
    title: "Transparency to deployers",
    phase: "Manage",
    description: "Providers of high-risk AI must supply instructions-for-use covering intended purpose, performance, risks, and human oversight measures.",
    check: (m) => {
      if (highRiskSystems(m).length === 0) return "not-applicable";
      return "fail";
    },
    evidence: (m) => {
      const hr = highRiskSystems(m);
      if (hr.length === 0) return "No high-risk AI systems detected.";
      return `Deployer-facing instructions-for-use not detected. Required for: ${listProviders(hr)}. Generated as part of the model-card artifact in Sub-phase D.`;
    },
  },

  {
    id: "ART-14",
    article: 14,
    title: "Human oversight",
    phase: "Manage",
    description: "High-risk AI must be designed so humans can oversee its operation, intervene, and override outputs.",
    check: (m) => {
      if (highRiskSystems(m).length === 0) return "not-applicable";
      const reviews = m.accessControls.requiredReviews ?? 0;
      if (reviews >= 1) return "partial";
      return "fail";
    },
    evidence: (m) => {
      if (highRiskSystems(m).length === 0) return "No high-risk AI systems detected.";
      const reviews = m.accessControls.requiredReviews ?? 0;
      if (reviews >= 1) {
        return `Branch protection requires ${reviews} reviewer(s) — code-level oversight present. Article 14 additionally requires runtime oversight (ability to interrupt, override, or stop the AI system) — document the human-in-the-loop design for each high-risk system.`;
      }
      return "No required PR reviewers configured. Both code-level review and runtime human-in-the-loop are needed for high-risk AI.";
    },
  },

  {
    id: "ART-50",
    article: 50,
    title: "Transparency obligations for providers and users",
    phase: "Manage",
    description: "Users interacting with AI systems, or receiving AI-generated content (text, image, audio, video), must be informed.",
    check: (m) => {
      if (transparencyScopeSystems(m).length === 0) return "not-applicable";
      if (m.artifacts.aiUsagePolicy === "present") return "pass";
      if (m.artifacts.termsOfService === "missing" && m.artifacts.privacyPolicy === "missing") return "fail";
      return "partial";
    },
    evidence: (m) => {
      const scope = transparencyScopeSystems(m);
      if (scope.length === 0) return "No user-facing AI systems detected — Article 50 does not apply.";
      if (m.artifacts.aiUsagePolicy === "present") {
        return `AI usage policy generated and present at ai-usage-policy.md, listing all ${scope.length} user-facing AI system(s) and the transparency obligations for each.`;
      }
      const tos = m.artifacts.termsOfService;
      const priv = m.artifacts.privacyPolicy;
      if (tos === "missing" && priv === "missing") {
        return "No ToS, privacy policy, or AI usage policy present to declare AI use. Required for: " + listProviders(scope);
      }
      return `Terms of service: ${tos}; privacy policy: ${priv}. No dedicated AI usage policy detected — the scanner will generate one on the next run when AI systems are present. Required for: ${listProviders(scope)}`;
    },
  },

  {
    id: "ART-60",
    article: 60,
    title: "EU database registration",
    phase: "Manage",
    description: "Providers of stand-alone high-risk AI must register the system in the EU public database before placing on the market.",
    check: (m) => {
      if (euMarketHighRisk(m).length === 0) return "not-applicable";
      return "fail";
    },
    evidence: (m) => {
      const scoped = euMarketHighRisk(m);
      if (scoped.length === 0) return "No EU-market high-risk AI systems detected — registration not required.";
      return `Registration in the EU database is required before market placement for: ${listProviders(scoped)}. Scanner cannot verify registration — track out-of-band and record the registration ID in your compliance documentation.`;
    },
  },

  {
    id: "ART-73",
    article: 73,
    title: "Reporting of serious incidents",
    phase: "Manage",
    description: "Providers of high-risk AI must report serious incidents to the relevant market surveillance authority without undue delay.",
    check: (m) => {
      if (highRiskSystems(m).length === 0) return "not-applicable";
      if (m.artifacts.incidentResponsePlan === "missing") return "fail";
      return "partial";
    },
    evidence: (m) => {
      if (highRiskSystems(m).length === 0) return "No high-risk AI systems detected.";
      if (m.artifacts.incidentResponsePlan === "missing") {
        return "No incident response plan present — required baseline for serious-incident reporting under Article 73.";
      }
      return `Incident response plan: ${m.artifacts.incidentResponsePlan}. Verify it includes AI-specific incident types (hallucination causing harm, discrimination, unexpected autonomy) and the market-surveillance-authority notification timeline (without undue delay, in any event within 15 days).`;
    },
  },
];

// ─── Evaluation ─────────────────────────────────────────────────────────────

export function evaluateEUAIAct(manifest: Manifest): AIComplianceResult[] {
  return EU_AI_ACT_CONTROLS.map(control => {
    const status = control.check(manifest);
    const evidence = control.evidence(manifest);
    const cross = getAICrossMapping(control.id);
    return {
      articleId: control.id,
      article: control.article,
      title: control.title,
      phase: control.phase,
      description: control.description,
      status,
      evidence,
      nistAiRmf: cross?.nistAiRmf ?? [],
      iso42001: cross?.iso42001 ?? [],
    };
  });
}

export function calcAIComplianceScore(results: AIComplianceResult[]): number {
  const applicable = results.filter(r => r.status !== "not-applicable");
  if (applicable.length === 0) return 100;
  const passed = applicable.filter(r => r.status === "pass").length;
  const partial = applicable.filter(r => r.status === "partial").length;
  return Math.round(((passed + partial * 0.5) / applicable.length) * 100);
}

export interface AIPhaseScore {
  name: AIRmfPhase;
  percentage: number;
  passed: number;
  partial: number;
  failed: number;
  applicable: number;
}

export function getAIPhaseScores(results: AIComplianceResult[]): AIPhaseScore[] {
  const phases: AIRmfPhase[] = ["Govern", "Map", "Measure", "Manage"];
  return phases.map(phase => {
    const phaseResults = results.filter(r => r.phase === phase);
    const applicable = phaseResults.filter(r => r.status !== "not-applicable");
    const passed = applicable.filter(r => r.status === "pass").length;
    const partial = applicable.filter(r => r.status === "partial").length;
    const failed = applicable.filter(r => r.status === "fail").length;
    const pct = applicable.length > 0
      ? Math.round(((passed + partial * 0.5) / applicable.length) * 100)
      : 100;
    return { name: phase, percentage: pct, passed, partial, failed, applicable: applicable.length };
  });
}
