import { SiteConfig } from "../config.js";

/**
 * Generates a security.txt file following RFC 9116.
 * https://www.rfc-editor.org/rfc/rfc9116
 *
 * Required fields: Contact, Expires
 * Recommended fields: Preferred-Languages, Canonical, Policy
 *
 * Expires is stable: pinned to Jan 1 of next year (00:00 UTC). This makes
 * generation idempotent within a calendar year — scans in 2026 always
 * produce `Expires: 2027-01-01T00:00:00.000Z`. File only changes at year
 * boundary or when config changes.
 */
export function generateSecurityTxt(config: SiteConfig): string {
  const now = new Date();
  const expires = new Date(Date.UTC(now.getUTCFullYear() + 1, 0, 1, 0, 0, 0, 0));

  const contact = config.securityContact || config.contactEmail;
  const siteUrl = config.siteUrl.replace(/\/$/, "");

  const lines: string[] = [
    `# Security policy for ${config.siteName}`,
    `# Generated by GRC Observability Dashboard`,
    `# https://securitytxt.org/ | RFC 9116`,
    ``,
    `Contact: mailto:${contact}`,
    `Expires: ${expires.toISOString()}`,
  ];

  if (siteUrl) {
    lines.push(`Canonical: ${siteUrl}/.well-known/security.txt`);
    lines.push(`Policy: ${siteUrl}/security-policy`);
  }

  lines.push(`Preferred-Languages: ${config.preferredLanguages.join(", ")}`);
  lines.push(``);

  return lines.join("\n");
}
