import { SiteConfig } from "../config.js";

/**
 * Generates a security.txt file following RFC 9116.
 * https://www.rfc-editor.org/rfc/rfc9116
 *
 * Required fields: Contact, Expires
 * Recommended fields: Preferred-Languages, Canonical, Policy
 */
export function generateSecurityTxt(config: SiteConfig): string {
  // Expires 1 year from generation — RFC 9116 requires this field
  const expires = new Date();
  expires.setFullYear(expires.getFullYear() + 1);

  const contact = config.securityContact || config.contactEmail;
  const siteUrl = config.siteUrl.replace(/\/$/, "");

  const lines: string[] = [
    `# Security policy for ${config.siteName}`,
    `# Generated by GRC Observability Dashboard`,
    `# https://securitytxt.org/ | RFC 9116`,
    ``,
    `Contact: mailto:${contact}`,
    `Expires: ${expires.toISOString()}`,
  ];

  if (siteUrl) {
    lines.push(`Canonical: ${siteUrl}/.well-known/security.txt`);
    lines.push(`Policy: ${siteUrl}/security-policy`);
  }

  lines.push(`Preferred-Languages: ${config.preferredLanguages.join(", ")}`);
  lines.push(``);

  return lines.join("\n");
}
