import { Manifest } from "../types.js";
import { SiteConfig } from "../config.js";

export interface HeaderRecommendation {
  header: string;
  value: string;
  status: "missing" | "present" | "partial";
  priority: "critical" | "high" | "medium";
  description: string;
}

export function generateHeaderRecommendations(
  manifest: Manifest,
  config: SiteConfig
): HeaderRecommendation[] {
  const h = manifest.securityHeaders;
  if (!h) return [];

  const _siteUrl = config.siteUrl.replace(/\/$/, "");
  const recommendations: HeaderRecommendation[] = [];

  // HSTS
  recommendations.push({
    header: "Strict-Transport-Security",
    value: "max-age=31536000; includeSubDomains",
    status: h.hsts,
    priority: "critical",
    description: "Tells browsers to only connect via HTTPS. Prevents SSL stripping and downgrade attacks.",
  });

  // X-Content-Type-Options
  recommendations.push({
    header: "X-Content-Type-Options",
    value: "nosniff",
    status: h.xContentTypeOptions,
    priority: "high",
    description: "Prevents browsers from MIME-type sniffing. Stops attacks where a file is served as a different content type.",
  });

  // X-Frame-Options
  recommendations.push({
    header: "X-Frame-Options",
    value: "DENY",
    status: h.xFrameOptions,
    priority: "high",
    description: "Prevents your site from being embedded in iframes. Stops clickjacking attacks.",
  });

  // Referrer-Policy
  recommendations.push({
    header: "Referrer-Policy",
    value: "strict-origin-when-cross-origin",
    status: h.referrerPolicy,
    priority: "medium",
    description: "Controls how much URL information is sent to other sites when a user clicks a link. Prevents leaking internal paths.",
  });

  // Permissions-Policy
  recommendations.push({
    header: "Permissions-Policy",
    value: "camera=(), microphone=(), geolocation=(), payment=()",
    status: h.permissionsPolicy,
    priority: "medium",
    description: "Disables browser features you don't use. Reduces attack surface if your site is ever compromised.",
  });

  // CSP — the complex one, built from scan findings
  const cspDirectives: string[] = [
    "default-src 'self'",
  ];

  // Check if the site uses inline scripts (HTMX likely does)
  cspDirectives.push("script-src 'self' 'unsafe-inline'");

  // Check for external script sources
  const hasGoogleAnalytics = manifest.dataCollection.some(d =>
    d.type === "tracking" && d.processor === "Google Analytics"
  );
  const scriptSources: string[] = [];
  if (hasGoogleAnalytics) {
    scriptSources.push("https://www.googletagmanager.com", "https://www.google-analytics.com");
  }
  if (scriptSources.length > 0) {
    cspDirectives[cspDirectives.length - 1] += " " + scriptSources.join(" ");
  }

  cspDirectives.push("style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com");
  cspDirectives.push("font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com");
  cspDirectives.push("img-src 'self' data: https:");
  cspDirectives.push("connect-src 'self'" +
    (hasGoogleAnalytics ? " https://www.google-analytics.com" : "")
  );
  cspDirectives.push("frame-ancestors 'none'");
  cspDirectives.push("base-uri 'self'");
  cspDirectives.push("form-action 'self'");

  recommendations.push({
    header: "Content-Security-Policy",
    value: cspDirectives.join("; "),
    status: h.csp,
    priority: "critical",
    description: "Controls what resources the browser is allowed to load. Primary defense against XSS attacks. This value is auto-generated based on your site's detected resources — test thoroughly before deploying.",
  });

  return recommendations;
}

export function generateExpressMiddleware(recommendations: HeaderRecommendation[]): string {
  const lines = recommendations.map(r =>
    `  res.setHeader('${r.header}', '${r.value.replace(/'/g, "\\'")}');`
  );

  return `// Security headers middleware — auto-generated by GRC scanner
// Add this near the top of your Express app, before routes
app.use((req, res, next) => {
${lines.join("\n")}
  next();
});`;
}

export function generateHeaderReport(recommendations: HeaderRecommendation[]): string {
  const lines: string[] = [
    "# Security Headers Report\n",
    "## Current Status\n",
    "| Header | Status | Priority |",
    "|--------|--------|----------|",
  ];

  for (const r of recommendations) {
    const statusIcon = r.status === "present" ? "PASS" : r.status === "partial" ? "PARTIAL" : "FAIL";
    lines.push(`| ${r.header} | ${statusIcon} | ${r.priority} |`);
  }

  const missing = recommendations.filter(r => r.status !== "present");

  if (missing.length > 0) {
    lines.push("\n## Recommendations\n");
    for (const r of missing) {
      lines.push(`### ${r.header}`);
      lines.push(`- **Priority:** ${r.priority}`);
      lines.push(`- **Value:** \`${r.value}\``);
      lines.push(`- **Why:** ${r.description}`);
      lines.push("");
    }

    lines.push("## Express Middleware (starter)\n");
    lines.push("```typescript");
    lines.push(generateExpressMiddleware(missing));
    lines.push("```\n");
    lines.push("**CSP caveat.** The `Content-Security-Policy` value above is generated from resources visible in the site's root HTML. Third-party CDNs loaded dynamically (unpkg, jsdelivr, cdnjs), inline scripts injected by frameworks, and analytics beacons from SPAs often aren't captured and will need to be added by hand before the policy becomes enforceable. Start by deploying with `Content-Security-Policy-Report-Only` and tighten from there.\n");

    lines.push("## Nginx Config (if using reverse proxy)\n");
    lines.push("```nginx");
    for (const r of missing) {
      lines.push(`add_header ${r.header} "${r.value}";`);
    }
    lines.push("```\n");
  } else {
    lines.push("\nAll security headers are present.\n");
  }

  return lines.join("\n");
}
