import type { AIEnhancements } from "./enhance.js";
import type { Risk } from "../generators/risk-assessment.js";
import type { SiteConfig } from "../config.js";

export function generateAIReport(
  enhancements: AIEnhancements,
  risks: Risk[],
  config: SiteConfig
): string {
  const lines: string[] = [
    `# AI-Enhanced Compliance Analysis — ${config.siteName}\n`,
    `*Generated by GRC Observability Dashboard AI module*\n`,
    "---\n",
  ];

  // PII Classifications
  if (enhancements.piiClassifications.length > 0) {
    lines.push("## PII Classification\n");
    lines.push("The following form fields were classified by AI for GDPR data category mapping:\n");
    lines.push("| Field | Category | GDPR Category | Confidence | Location |");
    lines.push("|-------|----------|---------------|------------|----------|");

    for (const c of enhancements.piiClassifications) {
      lines.push(`| ${c.field} | ${c.category} | ${c.gdprCategory} | ${c.confidence} | \`${c.location}\` |`);
    }
    lines.push("");

    // Detail reasoning
    lines.push("### Classification Reasoning\n");
    for (const c of enhancements.piiClassifications) {
      lines.push(`- **${c.field}:** ${c.reasoning}`);
    }
    lines.push("\n---\n");
  }

  // Enhanced risk narratives
  if (enhancements.riskNarratives.size > 0) {
    lines.push("## Risk Narratives (AI-Enhanced)\n");
    lines.push("Plain-English explanations of each risk with business context:\n");

    for (const risk of risks) {
      const narrative = enhancements.riskNarratives.get(risk.id);
      if (narrative) {
        lines.push(`### ${risk.id}: ${risk.title}\n`);
        lines.push(`> ${narrative}\n`);
      }
    }
    lines.push("---\n");
  }

  // Gap analysis
  if (enhancements.gapAnalysis) {
    lines.push("## Gap Analysis & Recommendations\n");
    lines.push(enhancements.gapAnalysis);
    lines.push("\n---\n");
  }

  // PR summary
  if (enhancements.prSummary) {
    lines.push("## PR Comment Preview\n");
    lines.push("This is the comment that would be posted on a PR:\n");
    lines.push("---\n");
    lines.push(enhancements.prSummary);
    lines.push("\n---\n");
  }

  return lines.join("\n");
}
